# Generated by Django 6.0.4 on 2026-06-16 15:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Filial nomi')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqam 901234567 formatida bo'lishi kerak.", regex='^\\d{9}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Kategoriya nomi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Agent ismi')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Mijoz ismi')),
                ('items', models.CharField(max_length=500, verbose_name='Mahsulotlar')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jami')),
                ('date', models.DateField(verbose_name='Sana')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_delivery', 'Yetkazilmoqda'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holat')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apps.agent')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_orders', to='apps.branch')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='apps.branch', verbose_name='Filial'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, verbose_name='Foydalanuvchining nomi')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam 901234567 formatida bo'lishi kerak.", regex='^\\d{9}$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('boss', 'Boss'), ('owner', 'Egasi'), ('manager', 'Menejer'), ('cashier', 'Kassir')], default='cashier', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='apps.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqam 901234567 formatida bo'lishi kerak.", regex='^\\d{9}$')])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='apps.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebtCustomers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255, verbose_name='Mijoz ismi')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqam 901234567 formatida bo'lishi kerak.", regex='^\\d{9}$')])),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Balans')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to='apps.branch')),
            ],
            options={
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='PosCartDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120, verbose_name='Nom')),
                ('pay_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('mixed', 'Aralash')], default='cash', max_length=20, verbose_name="To'lov turi")),
                ('items', models.JSONField(default=list, verbose_name='Mahsulotlar')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_cart_drafts', to='apps.branch', verbose_name='Filial')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_cart_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Kassir')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Shtrix-kod')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotuv narxi')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tannarx')),
                ('emoji', models.CharField(blank=True, default='📦', max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('status', models.CharField(choices=[('available', 'Mavjud'), ('out_of_stock', 'Tugagan'), ('draft', 'Qoralama')], default='available', max_length=20, verbose_name='Holat')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Qoldiq')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='apps.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='apps.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Tashqi ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('time', models.TimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('mixed', 'Aralash')], default='cash', max_length=20, verbose_name="To'lov turi")),
                ('cashier_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Kassir ismi')),
                ('items', models.JSONField(default=list, verbose_name='Mahsulotlar')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='apps.branch', verbose_name='Filial')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-external_id'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('charge', 'Qarz'), ('payment', "To'lov")], max_length=20, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='Izoh')),
                ('cashier_name', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='apps.debtcustomers', verbose_name='Hisob')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='apps.sale', verbose_name='Sotuv')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='apps.sale', verbose_name='Sotuv')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], default='active', max_length=20, verbose_name='Holat')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Jami buyurtmalar')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='apps.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Tashqi ID')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255, verbose_name="Ta'minotchi nomi")),
                ('date', models.DateField(verbose_name='Sana')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='Qabul sanasi')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami summa')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Kutilmoqda'), ('in_delivery', 'Yetkazilmoqda'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holat')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='apps.branch')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='apps.supplier', verbose_name="Ta'minotchi")),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='apps.supplier', verbose_name="Ta'minotchi"),
        ),
        migrations.CreateModel(
            name='SupplierCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('default_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Standart narx')),
                ('item_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Turi')),
                ('size', models.CharField(blank=True, default='', max_length=50, verbose_name="O'lchami")),
                ('unit', models.CharField(blank=True, default='ta', max_length=20, verbose_name="O'lchov birligi")),
                ('barcode', models.CharField(blank=True, default='', max_length=50, verbose_name='Shtrix-kod')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_catalog_items', to='apps.product', verbose_name='Mahsulot')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='apps.supplier', verbose_name="Ta'minotchi")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('item_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Turi')),
                ('size', models.CharField(blank=True, default='', max_length=50, verbose_name="O'lchami")),
                ('unit', models.CharField(blank=True, default='ta', max_length=20, verbose_name="O'lchov birligi")),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='apps.purchaseorder', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_lines', to='apps.product', verbose_name='Mahsulot')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='apps.suppliercatalogitem', verbose_name='Katalog elementi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Ombor nomi')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='apps.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Miqdor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='apps.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apps.warehouse', verbose_name='Ombor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='debtcustomers',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__gt', '')), fields=('branch', 'phone'), name='unique_credit_branch_phone_when_set'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='unique_product_per_warehouse'),
        ),
    ]
